### ISSUE TITLE
Ember 1.3.0-beta link-to block helper fails to compile

### ISSUE THREAD

**Issue by cryptoquick** [machty/emblem.js#116]
Using:

```
DEBUG: Ember      : 1.3.0-beta.3
DEBUG: Ember Data : 1.0.0-beta.4
DEBUG: Handlebars : 1.2.0
DEBUG: jQuery     : 2.0.3 
```

...and `Emblem 0.3.5` / `grunt-emblem 0.1.0`

This works:
`= link-to 'Upload' 'upload'`

This does not:

```
= link-to 'upload'
  Upload
```

Fails with:
Warning: Cannot read property 'original' of undefined Use --force to continue.

**Comment by bartocc** [comment]
@machty 

could you have a look at https://github.com/antramm/broccoli-emblem-compiler/issues/9 and tell us if this is related or not ?

**Comment by Mannaio** [comment]
i have a question:

emblem and broccoli-emblem-compile versionr : "0.3.19" has dependencies handlebars 2.0.0"
emblem and broccoli-emblem-compile versionr : "0.3.16" has dependencies on which handlebars version?
