### ISSUE TITLE
CLI for hbs -> emblem and emblem -> hbs

### ISSUE THREAD

**Issue by darthdeus** [machty/emblem.js#15]
This would make it really easy to start with Emblem, especially for complex very complex templates, or even just to demo to people how awesome it really is :)

**Comment by nbudin** [comment]
My coworkers and I (mainly @jslate, really) have written an Emblem -> Handlebars converter, which we've made publicly available here: https://github.com/patientslikeme/emblem2hbs

If you have any questions, issues, etc, we'd love to hear from you and our issue tracker is open!

**Comment by stevehanson** [comment]
@nbudin, @jslate: awesome utility, thanks so much for building this and sharing! I just used it to convert my entire codebase of 50+ Emblem templates to Handlebars. I wrote a little ruby script that uses your tool to convert all the Emblem files in my codebase, and it worked like a charm: https://gist.github.com/stevehanson/1551ade88fc260081e52. Thanks again.

**Comment by nbudin** [comment]
Thanks @stevehanson!  Glad to hear it was helpful.

**Comment by tannerthayer** [comment]
used today thanks! @stevehanson
