### ISSUE TITLE
Handlebars inner-helper support or documentation missing

### ISSUE THREAD

**Issue by simcha** [machty/emblem.js#159]
I've found that 1.3 handlebars inner-helper can be used in a helper like this:

```
tooltiped-div tooltip=(I18n 'en.div')
```

I even started a fork to emblem-site to document it. But can't make it work with html attributes like "class":

```
div class=(I18n 'en.div')
```

Is it a bug or a future? Or is there a way to do it properly?

**Comment by jaschaephraim** [comment]
I'd like to know this too.
