### ISSUE TITLE
Partial shorthand Incompatibility w/ Ember-CLI

### ISSUE THREAD

**Issue by drewcovi** [machty/emblem.js#169]
Might be more specifically tied to the broccoli-ember-hbs-temlate-compiler

It's currently complaining for me that a partial can't be found.

`Uncaught Error: The partial partial-name could not be found`

replacing

`> partial-name`

with 

`partial 'partial-name'`

however seems to clear up the issue.

Note: Typically if a partial is missing the partial helper is the one complaining (instead of the hbs-template-compiler) ie:
`Uncaught Error: Assertion Failed: Unable to find partial with name 'partial-name'.`

**Comment by hooddanielc** [comment]
:+1: I am running to this issue as well. 

changing

```
partial 'path/to/partial'
```

to

```
partial 'path/to/partial'
```

is a workaround
