### ISSUE TITLE
Wrapping helper properties into multiple lines 

### ISSUE THREAD

**Issue by emoryy** [machty/emblem.js#171]
It's not included on emblemjs.com, so I've looked into the test specs, and I've found that it is possible to wrap properties into more lines with the use of brackets.
But it doesn't seem to work properly with Ember helpers, for example with `Ember.Select`
Static attributes are good (`class="something"`), however attribute bindings doesn't seem to work either in the form of `value=something` or `valueBinding="something"`.
This is what I tried:

```
Ember.Select [
  content=something
  optionValuePath="content.value"
  optionLabelPath="content.label"
  value=somethingValue
  class="something" ]
```

**Comment by kjhangiani** [comment]
Converting: 

    = inline-edit-select selectedOption=model.supervisorUser allOptions=filteredUsers prompt="Supervisor" name="supervisorUser" saveAction="updateControlsDatum"

To:

    inline-edit-select [
      selectedOption=model.supervisorUser 
      allOptions=filteredUsers
      prompt="Supervisor" 
      name="supervisorUser"
      saveAction="updateControlsDatum" ]

fails for me using ember-cli / emblem 0.5.0 and ember-cli-emblem-hbs-printer 0.2.1 with the following error:

    File: soxhub-client/templates/controls-datum/inline-form.emblem (16)
    Expected _1BeginStatement, _1DEDENT or end of input but "\uEFEF" found.

I have tried various positions on the brackets as well as indenting, but I cannot seem to get this to compile.  Am I doing something wrong?  inline-edit-select is an ember component
