### ISSUE TITLE
View documentation incorrect as of Ember 1.8 / views possibly unsupported?

### ISSUE THREAD

**Issue by lwisne** [machty/emblem.js#178]
Before Ember 1.8 came out, I could do:

```
Ember.Select content=options value=value
```

And this is how all the emblem guides suggest I should do things.  Now, doing that gives a deprecation warning:

"Resolved the view "Ember.Select" on the global context. Pass a view name to be looked up on the container instead, such as {{view "select"}}. http://emberjs.com/guides/deprecations#toc_global-lookup-of-views-since-1-8"

I read the guide on this, but I simply cannot get the new syntax to work in any way within emblem.  I'm not even sure it's supported at all.  Please advise - I can't be using a tempting engine that gives scary deprecation warnings on such basic functionality.

**Comment by thec0keman** [comment]
Closing in favor of #281
