### ISSUE TITLE
Better error messaging

### ISSUE THREAD

**Issue by stevehanson** [machty/emblem.js#180]
It would be awesome if we could get some better error messaging. The only error message I can recall seeing from Emblem is: 

```
Emblem syntax error, line x: Expected BeginStatement or DEDENT but "\uEFEF" found.
```

The problem is that the message is not very descriptive and doesn't help me identify the actual problem. `BeginStatement`, `DEDENT` and `\uEFEF` seem like implementation details that the user shouldn't have to be exposed to. Also, the line number is not usually meaningful. It usually is line 3 or 4, and I have not seen it correspond to the location of my actual error.

Thanks for your work on Emblem.js - great tool!

**Comment by Evkin** [comment]
+1 please

**Comment by kjhangiani** [comment]
Also +1, this is literally the only error message I have ever seen

**Comment by thec0keman** [comment]
Moved to #276
