### ISSUE TITLE
The JSBin examples mentioned in the docs are not working

### ISSUE THREAD

**Issue by suchitpuri** [machty/emblem.js#181]
Hi , The jsbin examples mentioned in the docs are not working , seems like some issues with the versions of other libraries
http://jsbin.com/ulegec/337/edit?html,console,output
http://jsbin.com/ucanam/4144/edit

```
"Script error. (line 0)"
"error"
"TypeError: Cannot read property 'create' of undefined
    at http://null.jsbin.com/runner:1:914"
"DEBUG: For more advanced debugging, install the Ember Inspector from        https://chrome.google.com/webstore/detail/ember-inspector/bmdblncegkenkacieihfhpjfppoconhi"
```

**Comment by thujeevan** [comment]
I've just created a working starter kit 

http://emberjs.jsbin.com/wicisehopi/2/edit?html,js,output

**Comment by thec0keman** [comment]
Closing in favor of #281
