### ISSUE TITLE
Doesn't work with ember 1.9 beta 3

### ISSUE THREAD

**Issue by piotrpalek** [machty/emblem.js#182]
I followed the upgrade guide for an ember-cli project on: http://emberjs.com/blog/2014/10/16/handlebars-update.html and after the upgrade, I get this error: Uncaught Error: Unknown template object: function, does emblem support handlebars 2.0?

**Comment by railsjedi** [comment]
I'm getting this issue trying to upgrade to ember-source 1.9.1 gem

@simcha's hack didn't seem to help (after rebundling and `rake assets:clobber`)

**Comment by paulb79** [comment]
@simcha thanks had the exact same issue as @phyllisstein but your advice fixed it.
