### ISSUE TITLE
'Else' that from 'if' is not working in Ember 1.10.0-beta.1

### ISSUE THREAD

**Issue by simcha** [machty/emblem.js#184]
Else clause is not reached in the code:
```
if friend
  //when friend true
else
  //never
unless friend
  //when friend = false
```
I made the jsbin to prove it: http://jsbin.com/yewajizopi/3/edit
And another one to check that handlebars version works ok: http://jsbin.com/qubaxesolo/1/edit
Ember version was  1.10.0-beta.1+canary.4460f88a

**Comment by romanbsd** [comment]
Looks like it's fixed in 0.3.19
