### ISSUE TITLE
New Handlebars' parser API

### ISSUE THREAD

**Issue by asermax** [machty/emblem.js#186]
In relation to #139, I was trying to make an Ember project work with [tildeio/htmlbars](https://github.com/tildeio/htmlbars) + emblem, but came to realize that htmlbars is using the new parser API discussed on wycats/handlebars.js#889
Given that, the AST provided by emblem is currently incompatible with htmlbars because some (minor, I think) changes on this new API.

I wouldn't mind trying to adapt emblem to the new API, but I'm not really sure were to start, would you mind giving me some pointers?

**Comment by asermax** [comment]
Tested your changes in my project and the parsing worked perfectly so far, the htmlbars precompiled didn't complain and the templates worked on the latest ember release. Only caveat was using the `ember-htmlbars-attribute-syntax` feature flag for bound attributes to work.
Thanks for the hard work!

Sill, looks like some libraries aren't htmlbars ready yet so what I could test was limited. I'll keep trying tho :)

**Comment by machty** [comment]
Closing this since we're not targeting Hbs AST any more; I'm finishing up work on an Emblem->Handlebars source compiler that'll take care of all of this
