### ISSUE TITLE
Looking for new/additional maintainer for Emblem.js

### ISSUE THREAD

**Issue by machty** [machty/emblem.js#189]
### edit: don't worry! Emblem is getting HTMLBars support momentarily!

I unfortunately don't have the time to maintain this project the way I'd like and would love to pass it off to an interested person. Certainly happy to explain code organization, plans for the future, integration with Handlebars/HTMLbars/Ember. Please let me know if you're interested!

**Comment by saponifi3d** [comment]
i could _help_ with maintaining, but i wouldn't be able to be the sole person on it.  also, any chance you can publish the latest to npm w/ handlebars 2.0.0? i'm trying to upgrade a few other projects that are using this as a dependency.

**Comment by cpuser** [comment]
We'll definitely need Emblem on top of HTMLBars. And if it helps we are happy to maintain the project.

**Comment by machty** [comment]
I'm getting Emblem working on top of HTMLBars as we speak, but after that it'd be nice to pass on the knowledge

**Comment by CNDW** [comment]
I have a project in production build with emblem, so I have a vested interest in at least helping to maintain. Where do I sign up?

**Comment by machty** [comment]
@CNDW I have some folk finishing up the HTMLbars migration, and after that's done, Emblem won't need as much work (perhaps none?) to keep up with Handlebars changes, so I'd feel comfortable continuing as "maintainer", but there are a lot of issues I won't get around to on my own and a lot of them seem open to aspiring contributors if you wanna look through those.

**Comment by brandonjmckay** [comment]
@machty I'm loving emblem, and I would love to contribute. I'm not sure what maintaining would entail, or what time commitment that would involve, but I'd be interested in helping at least some.

I'm just beginning to look through PegJS to get an understanding of how to contribute here. I was looking for a "How to Contribute" section—rules/guidelines—but couldn't find one. 

If you are passing along knowledge on how to care for it, would you be into a Google hangout with interested possible maintainers/contributors? I'd like to be a part of something like that.

**Comment by matthiasleitner** [comment]
@machty Now that ember 1.10 stable with HTMLbars is out any reports on the progress of fixing compatibility?

Happy to contribute to emblem in order to help it stay compatible with current ember versions.

**Comment by atsjj** [comment]
Hey @machty, is there a checklist or plan for the ember-cli branch?

I've been hacking on it, watching the latest fork and trying to learn as much as I can. I'd like to see if I can help out in any way...

**Comment by saponifi3d** [comment]
@machty - i can also take over some of this stuff if you want. i was about to start upgrading to handlebars@3.0.0 too. :beers:

**Comment by mixonic** [comment]
The merge of https://github.com/machty/emblem.js/pull/196 in imminent. I suggest taking a peek! No more Handlebars AST, for one.

**Comment by saponifi3d** [comment]
:dancers: kewl. thanks for the update :)
