### ISSUE TITLE
Please release 0.4.0 for handlebars 2.0 support

### ISSUE THREAD

**Issue by bjornstar** [machty/emblem.js#201]
As I mentioned in #197 please, please delete 0.3.19 from npm and re-release it as 0.4.0

Everyone using handlebars 1.3.0 who have ~0.3.18 as their dependency just got their builds broken by the 0.3.19 release.

Handlebars 2.0.0 is a major api change and deserves a minor version update in emblem.

**Comment by machty** [comment]
You're right. I unpublished 0.3.9 and published 0.4.0.
