### ISSUE TITLE
Inline HTML is not escaped

### ISSUE THREAD

**Issue by angelbotto** [machty/emblem.js#202]
![captura de pantalla 2015-02-26 a las 1 11 45 p m](https://cloud.githubusercontent.com/assets/266151/6398378/29461e2e-bdb9-11e4-9289-95fae795f006.png)

Using **html**  in a **.emblem** file, is not escaped and could be seen as a problem.

**Comment by bantic** [comment]
@angelbotto it doesn't appear to be explicitly documented in the docs, but inline raw HTML is supported. It is specifically tested for in the emblem tests here: https://github.com/machty/emblem.js/blob/master/test/qunit_spec.coffee#L460-L475

Please re-open if I misunderstood.
