### ISSUE TITLE
text blocks break when indenting after newlines

### ISSUE THREAD

**Issue by machty** [machty/emblem.js#21]
Expects `else` but gets end of input:

```
  div
    p
      span Butts
        em fpokasd
        iunw
          paosdk
```

fix for this will likely fix https://github.com/machty/emblem.js/issues/9 too

**Comment by thec0keman** [comment]
On master this currently outputs:
```
<div><p><span>Butts em fpokasd iunw paosdk</span></p></div>
```

Is that the expected result, or should there be an `<em>` tag in there?
