### ISSUE TITLE
Nested Elements Mixed with Handlebars

### ISSUE THREAD

**Issue by thec0keman** [machty/emblem.js#211]
This is failing for 0.5.0-beta:
```
div
  = thing
  div
    hr
```
with `Expected BeginStatement, DEDENT or end of input but "\uEFEF" found.`

I'm pretty sure this is from [this commit](https://github.com/machty/emblem.js/commit/e1a94ed9bae550d61f766255d8a0010f19f04c5b).

**Comment by bantic** [comment]
thanks, confirmed. Adding a failing test case and fixing this now

**Comment by mixonic** [comment]
Closed by https://github.com/machty/emblem.js/commit/961a8e239c34372d5cc0cf64a7deca037cf2efaa
