### ISSUE TITLE
Global mode for Emblem

### ISSUE THREAD

**Issue by mixonic** [machty/emblem.js#212]
Emblem should have a "global mode". We broke this in 0.5.0-beta.

In this mode a [bootstrap](https://github.com/machty/emblem.js/blob/3762f4b124a02a59389feb65f5955ce64147c4c8/lib/bootstrap.js) command should look for emblem template script tags and either a) compile those to Ember templates or b) compile them to raw templates, and write them into the DOM as Ember template `<script` tags.

**Comment by auvipy** [comment]
is this fixed? or milstone needs update

**Comment by thec0keman** [comment]
Since Ember strongly encourages precompiling templates, is there still a use case for this feature?
