### ISSUE TITLE
Status of Ember 1.10 features in 0.5.x branch

### ISSUE THREAD

**Issue by thec0keman** [machty/emblem.js#215]
Will these features be included in the 0.5.x branch?
- else if
- block params

**Comment by bantic** [comment]
@thec0keman `else if` works fine:
![image](https://cloud.githubusercontent.com/assets/2023/6423332/7ecf7daa-beb2-11e4-9463-3beefbf45c7d.png)

Block params probably need a new syntax in Emblem, right? Is there a facility for doing this in Emblem 0.4.0?

**Comment by bantic** [comment]
@thec0keman Oops, the else if does *not* work. This may also need a syntactic change to Emblem? But yes, we should support it.

**Comment by thec0keman** [comment]
Block params were not supported in 0.4.  I only did a small amount of testing with the 0.5 branch for this, but the compiler generally was confused with things like `= some-component as |content|`.

**Comment by mixonic** [comment]
@thec0keman our goal has really been to get Emblem running as a printer, not to add new features to it. Those are definitely valid features to add, but the answer to:

> Will these features be included in the 0.5.x branch?

Is:

> If you build it, they will come.

:-) I'm not in favor of blocking a 0.5.1 release on this new functionality.
