### ISSUE TITLE
Multiline attributes via brackets aren't working for views

### ISSUE THREAD

**Issue by snovity** [machty/emblem.js#219]
The following
```emblem
 view 'select' [
   content=theContent
   selection=theSelection ]
```
isn't working. Probably because of the view name `'select'` specified before brackets. In contrast
```emblem
input [
  type='password'
  value=theValue ]
```
is working.

**Comment by snovity** [comment]
Just found out that 
```emblem
 view [
  'select' 
   content=theContent
   selection=theSelection ]
```
works as expected.

**Comment by snovity** [comment]
Ok, I have to reopen the issue, because although specifying view name inside brackets doesn't trigger compile issues, when compiled it doesn't work.

**Comment by bantic** [comment]
@snovity thanks. I will try compiling this and see what the handlebars output is. Maybe it is not the expected value.

**Comment by bantic** [comment]
@snovity I think the issue may be that Emblem is compiling that into a block helper:

```
 view [
  'select' 
   content=theContent
   selection=theSelection ]
```

becomes:

```
 {{#view 'select' content=theContent selection=theSelection}}{{/view}}
```

Do you think that explains your issue?
You can play around with Emblem syntax to see how it will get compiled at this [try emblem site](http://bantic.github.io/try-emblem/)

**Comment by snovity** [comment]
@bantic it seems this is the case, for some reason adding a `'select'` triggers a block helper creation and it supplies a blank template to the view. The result is that view renders nothing.

**Comment by mixonic** [comment]
For views, a block template replaces a template on the view. This should probably not create a block without indented content.

**Comment by kjhangiani** [comment]
The 

    input [
      type='password'
      value=theValue ]

syntax does not work for me using ember 1.11, emblem 0.5, and ember-cli-emblem 0.27 (all latest afaik).  It also completely chokes if you do 

     = input [
            ...
           ]

This syntax is so much cleaner esp when working on a more complicated app with a lot of components (form fields in particular), there's a pull request to fix it as well, is there any chance this will get released soon?
