### ISSUE TITLE
Bracket attributes no longer support empty lines

### ISSUE THREAD

**Issue by paulcretu** [machty/emblem.js#223]
I upgraded from 0.4.0 to 0.5.0 and multiline attributes that contain empty lines no longer work. For example:

```
ember-component [
  isHidden=foo
  value=bar

  saveAction="save" ]
```

Lines that contain comments don't work either:

```
ember-component [
  isHidden=foo
  value=bar
  / here's a comment
  saveAction="save" ]
```

**Comment by bantic** [comment]
@paulcretu Thanks for this report. This likely relates to #219 as well.
