### ISSUE TITLE
Can we purrrrdy plz have a new release?

### ISSUE THREAD

**Issue by hhff** [machty/emblem.js#224]
I'm tryna to use #221 (index'd each) in an app I just upgraded to `Ember 0.1.11-beta.5` :smile: :heart: :hamburger:

**Comment by mixonic** [comment]
I've been hesitating since have literally 0% progress on our previous 0.5.1 goals :-/

https://github.com/machty/emblem.js/milestones/0.5.1

But yeah, we will not run out of numbers. I'll convert that milestone to 0.6.0 and make a release.

**Comment by hhff** [comment]
haha gotcha - yeah it would be good to have that minor version number up the sleeve for quick releases :)

**Comment by tolgaek** [comment]
:+1:
