### ISSUE TITLE
Expected _1BeginStatement, _1DEDENT or end of input but "\uEFEF" found.

### ISSUE THREAD

**Issue by cheerfulstoic** [machty/emblem.js#231]
I've search and searched but can't find an answer that quite matches.  I wonder if you can help?  I have the following template which worked using `ember-rails`:

```emblem.js
div.list-group
  each child in node
    model-list-item model=child.[0] sub_hierarchy=child.[1]
```

I'm trying to convert my gem to ember-cli but I'm getting:

```
Build failed.
File: ember-src/templates/components/model-list.emblem (2)
Expected _1BeginStatement, _1DEDENT or end of input but "\uEFEF" found.
```

After doing a lot of fiddling I've narrowed it down to it being the array index accessing.  If I remove the `.[0]` and `.[1]` it builds (but won't work, obviously).  I've tried removing the dot, I've tried `child.0`, but neither of those work.

**Comment by KurtRMueller** [comment]
I'm running into this right now. Have you found a solution yet?

**Comment by cheerfulstoic** [comment]
Nope ;(. It was a small template so I switched to using hbs for just that one template

**Comment by kjhangiani** [comment]
I've also run into this a few times and have resorted to hacking around the array index accessing via very useless computed properties... not an elegant solution but it works.

Hoping that some of these pending fixes get merged in soon...
