### ISSUE TITLE
Multiline tag definitions

### ISSUE THREAD

**Issue by thedeeno** [machty/emblem.js#237]
In WebComponent land we often have to pass many attributes to our components. In native html it ends up looking like this:

```
<my-custom-element
  id="foo"
  class="bar"
  cat="{{ dog }}"
  on-bark="{{ run }}"
>
  <p>content</p>
</my-cusomt-element>
```

I don't see an easy way to do this with emblem, but I think this approach would look nice:

```
my-custom-element#foo.bar {
  cat="{{ dog }}"
  on-bark="{{ run }}"
}
  %p content
```

Thoughts? Is there a way to do multiline tags already?

**Comment by coladarci** [comment]
you seem to be mixing a lot of things together.. you mention `components` but your use of `#foo.bar` is specifically for elements, not for components. Then you add `{{ }}` which is handlebars inside emblem.. 

Having said all of that, it's possible:

```
your-component[
  foo='bar'
  biz=bang
  ]
```

**Comment by thedeeno** [comment]
Web components as in the html-custom-elements-spec, not ember components. Basically using something like polymer-elements within my ember app. The syntax shown there is exactly what I'm looking for though! Thanks.
