### ISSUE TITLE
Got \uefff symbol on new line in text param of a component

### ISSUE THREAD

**Issue by cgwic** [machty/emblem.js#249]
simple example:
```emblem
test-component param='
'

emblem version: 0.5.1

**Comment by thec0keman** [comment]
Yeah, this makes a lot of sense based on the way emblem parses things.

Is there a use case for having newlines inside text parameters?  It looks like Ember escapes these: [jsbin](http://emberjs.jsbin.com/leyikiyode/edit?html,js,output).

**Comment by cgwic** [comment]
@thec0keman I'm not sure, but i can't find the way to pass an object as a param, so i solved this by passing string and then parsing it
May be there's better way

In my case i've just made w/a with replacing these symbols so it's not a problem if it's emblem feature

**Comment by thec0keman** [comment]
Do you mean like the following?
`= some-component value={ foo: 'bar' }`

I don't think Ember supports this.  You would need to define the object on the template's context (controller / component) instead.

**Comment by kjhangiani** [comment]
Would be awesome if ember would support that syntax though... definitely situations where being able to define an object, or at the very least an array inline would be supremely helpful.

**Comment by cgwic** [comment]
@thec0keman yes, it doesnt. So i use something like:
``` javascript
some-component value='{
"val1": "val1",
"val1": "val1"
}'
and parse it in component.

So now i see that this is a feature with \uefff on line ending and now with replace before parsing everything works fine. Thank you for help.
