### ISSUE TITLE
Error using the new syntax "each XX as |YYY"

### ISSUE THREAD

**Issue by frisco82** [machty/emblem.js#255]
I am unable to generate a correct result to use new each syntax as shown here:
http://guides.emberjs.com/v2.1.0/templates/displaying-a-list-of-items/

```each model as |card``` Does not work
```{#each model as |card}``` Also does not work

Probably there is some way to overcome this but I am unable to find it.
I am using ember-cli-emblem but also have tried with http://bantic.github.io/try-emblem/ with the same results

**Comment by thec0keman** [comment]
`= each model as |card|` works for me.  Are you including the closing pipe?

**Comment by thec0keman** [comment]
(Also, unfortunately the try-emblem site is a few versions of out date)

**Comment by frisco82** [comment]
Ok using that sintaxis works without issues, 
what it is exactly that double pipe? I haven't seen it in the documentation.

**Comment by thec0keman** [comment]
It's Ember's block param syntax: http://emberjs.com/blog/2015/02/07/ember-1-10-0-released.html#toc_block-params
