### ISSUE TITLE
small typo prints blank page, may be worth adding an error

### ISSUE THREAD

**Issue by Leooo** [machty/emblem.js#256]
Took me one hour to find that a small typo in one of my embl templates was causing the page to render nothing, without any error message. Just thought it may be worth signalling it in case it is possible to detect this case and print a compile error when it occurs:
`````
| This line will not be rendered at all when there is the typo below
a. click="destroyModel"
| This line will not be rendered at all when there is the typo above
`````

=> typo is in the `````a.`````, should be only `````a`````

**Comment by thec0keman** [comment]
Moved to #276
