### ISSUE TITLE
compiling to deprecated handlebars

### ISSUE THREAD

**Issue by Kallin** [machty/emblem.js#257]
I've pulling in emlem via ember-cli-emblem for my ember app, and am noticing the warning:

DEPRECATION: Using the '{{#each item in model}}' form of the {{#each}} helper ('test-app/templates/search/cards.hbs' @ L1:C23) is deprecated. Please use the block param form instead ('{{#each model as |item|}}'). See http://emberjs.com/guides/deprecations/#toc_code-in-code-syntax-for-code-each-code for more details.

from the ember template compiler. I believe the emblem files are translated to hbs files, and then the ember compiler is raising this warning. Does it seem like something to fix here? I could take a look and offer a PR if it's agreeable.

**Comment by thec0keman** [comment]
What does your emblem template look like?

` = each model as |item| ` works in emblem currently.
However, emblem will not compile ` = each item in model ` to the block param format.

**Comment by Kallin** [comment]
@thec0keman Ah that did it, sorry for being such a noob!

**Comment by thec0keman** [comment]
No worries, glad I could help :)
