### ISSUE TITLE
No updates for a while

### ISSUE THREAD

**Issue by trobrock** [machty/emblem.js#258]
It looks like there haven't been any updates to this repo for a little while, we are deciding as a team whether to stick with emblem or not. @machty are you still planning on maintaining this project or is it dying out a bit?

**Comment by spinlock99** [comment]
It looks like there was a good deal of work done at the beginning of the year. I'm actually just starting a new project and putting emblem in from the start. My guess is that it won't do everything and we'll need to have some HTMLBars tempting around for the newest features. But, in my mind, it's worth it to work in a nice language for all of the boilerplate.

**Comment by thec0keman** [comment]
We have a pretty large Ember app and haven't run into any issues with the latest version of Emblem.  The biggest thing missing right now is angle bracket components.  I have been hoping to start picking at that, but time. :)

**Comment by coladarci** [comment]
I'm in love w/ Emblem and when there was talk of it disappearing a while back, the community rallied around it.

**Comment by trobrock** [comment]
Ok, well I should say we've been using it for over a year and a half and love it, but just recently upgrade to ember-cli and figured we would evaluate all the tools we are using. Looks like there is still a great community around this project and we will be sticking with it.
