### ISSUE TITLE
Extra "/" in generated component tests

### ISSUE THREAD

**Issue by andrewtimberlake** [machty/emblem.js#259]
When running `ember g component test-component --pod` the generated test has an extra slash in each handlebars component statement.
Instead of 
```javascript
this.render(hbs`{{test-component}}`);
//...
this.render(hbs`
  {{#test-component}}
    template block text
  {{/test-component}}
`);
```
the output is
```javascript
this.render(hbs`{{/test-component}}`);
//...
this.render(hbs`
  {{#/test-component}}
    template block text
  {{//test-component}}
`);
```
I only get this issue on projects that use emblem.

Environment:
Ember      : 2.2.0
Ember Data : 2.2.0
jQuery     : 2.1.4

**Comment by machty** [comment]
I think this is actually an issue for https://github.com/Vestorly/ember-cli-emblem, would you mind opening one there?

**Comment by andrewtimberlake** [comment]
Thank you, I have done that.
