### ISSUE TITLE
Inverse yielding requires unexpected indentation

### ISSUE THREAD

**Issue by SaladFork** [machty/emblem.js#266]
**NOTE:** The examples in this comment are not actually correct as I had not properly simplified the problem. Please see [my correction in a follow-up comment](https://github.com/machty/emblem.js/issues/266#issuecomment-208509362).

---

```slim
/ only way that works
some-component-with-inverse-yield
  | foo
  else
  | bar

/ doesn't work (this is what I'd expect to work)
some-component-with-inverse-yield
  | foo
else
  | bar

/ doesn't work
some-component-with-inverse-yield
  | foo
  else
    | bar
```

The ones that don't work result in an error:
> `Uncaught Error: Assertion Failed: A helper named 'else' could not be found`

Equivalent handlebars:
```handlebars
{{#some-component-with-inverse-yield}}
  foo
{{else}}
  bar
{{/some-component-with-inverse-yield}}
```

**Comment by thec0keman** [comment]
@SaladFork  can you confirm if this is still an issue?

I am seeing the following working:
```
some-component-with-inverse-yield
  |foo
else
  |bar

=> 
{{#some-component-with-inverse-yield}}
  foo
{{else}}
  bar
{{/some-component-with-inverse-yield}}
```

**Comment by SaladFork** [comment]
Ah, my mistake. As posted you are correct. I've done some more research and the fail condition is when you switch to multi-line declarations with square brackets:
```slim
/ works
some-component-with-inverse-yield value=true
  | foo
else
  | bar

/ doesn't work
some-component-with-inverse-yield [
  value=true ]
  | foo
else
  | bar

/ works
some-component-with-inverse-yield [
  value=true ]
  | foo
  else
  | bar
```

**Comment by thec0keman** [comment]
[#274](https://github.com/machty/emblem.js/pull/274) should resolve this
