### ISSUE TITLE
Support slim-like attributes wrapper

### ISSUE THREAD

**Issue by mreq** [machty/emblem.js#269]
Convenient when working with many arguments (e.g. Ember passing on actions). Also simplifies git diffs a lot.

http://www.rubydoc.info/gems/slim/frames#Attributes_wrapper

Now:

```emblem
custom-component foo=foo bar=bar foobar="foobar" barfoo="barfoo"
````

After:

```emblem
custom-component(
  foo=foo
  bar=bar
  foobar="foobar"
  barfoo="barfoo"
)
```

**Comment by coladarci** [comment]
'''
foo-bar[
  biz=bang
  ]
'''

**Comment by mreq** [comment]
Thanks, that will do :)
