### ISSUE TITLE
Can't use $ as an attribute name

### ISSUE THREAD

**Issue by bnetter** [machty/emblem.js#279]
I sometimes prefix my attributes with `$`, as `$amount`. Then, when using it on my templates, I get the following error:

``` js
emblem/parser.js:7689
      throw peg$buildException(null, peg$maxFailExpected, peg$maxFailPos);
      ^
SyntaxError: Expected _4BeginStatement or end of input but "\uEFEF" found.
```

Example code:

``` js
div= transaction.$amount
```

**Comment by bnetter** [comment]
Same when you use this as attributes.

```slim
component-name amount=transaction.$amount
```

**Comment by kketch** [comment]
@bnetter it seems that attributes with the "$" characters are incompatible with the cases you mention here.
But you can work around it today with this syntax in your first case: 
  `div #{transaction.$amount}`

And in the second case:
  `component-name amount=(get transaction '$amount')`
Or:
  `component-name amount='#{transaction.$amount}'`

**Comment by tmosmant** [comment]
Thanks @kketch, first syntax works (we were aware of this one but it's a proper workaround), second one won't work unless you're running Ember 2.1.0 for the `get` keyword (sadly that's not our case yet) and the last one simply transmits a `#{transaction.$amount}` string. Still, except than maybe write a `get` helper before going 2.1.0, we're unable to prefix our properties with `$`.

**Comment by kketch** [comment]
@tmosmant I'll look soon for a fix, it looks like a parser bug

**Comment by thec0keman** [comment]
I'm not 100% sure, but I suspect [this](https://github.com/machty/emblem.js/blob/master/lib/pegjs/mustache/name-character.pegjs) may be a good place to start.
