### ISSUE TITLE
Syntax documentation lagging behind

### ISSUE THREAD

**Issue by bvellacott** [machty/emblem.js#281]
Hi - I'm new to emblem and I noticed the syntax documentation is lagging behind quite a bit. You're missing things like 'each-in' and instead of having 'each item in model' it's now 'each model as |item|'. Hinders learning quite a bit, although I can guess what's going on from knowing a bit of handlebars. Might be useful to at least direct to the documentation for handlebars and htmlbars though. If there's an easy way of contributing to this as a newbie, I'm happy to contribute.

B

**Comment by thec0keman** [comment]
@bvellacott  I completely agree.  I have a WIP branch I need to finish up.  I'm sure after that gets up there will still be a large amount of room for improvement, so any contributions would be appreciated. :)

The documentation site is [here](https://github.com/machty/emblem-site).

**Comment by bvellacott** [comment]
Cheers

B

----- Alkuperäinen viesti -----
Lähettäjä: "John Ratcliff" <notifications@github.com>
Lähetetty: ‎30/‎06/‎2016 17:07
Vastaanottaja: "machty/emblem.js" <emblem.js@noreply.github.com>
Kopio: "Benjamin Vellacott" <bmvellacott@gmail.com>; "Mention" <mention@noreply.github.com>
Aihe: Re: [machty/emblem.js] Syntax documentation lagging behind (#281)

@bvellacott I completely agree. I have a WIP branch I need to finish up. I'm sure after that gets up there will still be a large amount of room for improvement, so any contributions would be appreciated. :)
The documentation site is here.

**Comment by woohoou** [comment]
Hi @thec0keman!, thanks for your effort, do you have any news with this ticket?

Thanks!
