### ISSUE TITLE
DEPRECATION: Explicit component declarations will be interpreted as angle-bracket components in a later release

### ISSUE THREAD

**Issue by danielspaniel** [machty/emblem.js#286]
Howdy, 
 I upgraded to 0.8  and I am getting deprecations. 

 I found ( in other issues ) that you are preparing to support glimmer components and need to differentiate between components, html tags and glimmer components. 

 But I am not sure what the proper syntax is in this new version and can't seem to get rid of those deprecations.

 Can you give me a clue or two?

**Comment by thec0keman** [comment]
Could you specify which deprecation notices are being thrown?

**Comment by danielspaniel** [comment]
That question made me look at the deprecation one more time, and then look right below it:

DEPRECATION: Explicit component declarations will be interpreted as angle-bracket components in a later release: project-units
File: schema-ember/templates/stacking/-area-driven-properties.emblem

where is says the File name

 I was confused because project-units is also a file .. but clearly the message was telling me where to look and what to look at. So I this is a quality facepalm. 

I am going to close this, but just might be nice to have a blurb when the angle brackets are supported to know how to set up the syntax for those.

**Comment by thec0keman** [comment]
Yeah we should put together a quick guide here about what some of those mean.

The goal is eventually to make this be an angle bracket component:
```
my-component foo=bar
```
and this be the traditional component:
```
= my-component foo=bar
```

Thanks!

**Comment by joykeeper** [comment]
The new syntax is mentioned here http://emblemjs.com/idioms/ but deprecated version still persists here http://emblemjs.com/syntax/ which is confusing and led me to this ticket.

**Comment by ELLIOTTCABLE** [comment]
As @anton-iskandiarov noted, the docs still suggest using `link-to` without the `=` syntax — not just on http://emblemjs.com/syntax/, but also on http://emblemjs.com/idioms/.

(Maybe open a seperate documentation-Issue, @anton-iskandiarov? `(=`)

**Comment by thec0keman** [comment]
Yeah, the docs are very out of date :(   I think this is one of the biggest needs for Emblem right now
