### ISSUE TITLE
Breaks with Glimmerjs

### ISSUE THREAD

**Issue by remzr7** [machty/emblem.js#295]
Emblem only works with ember but not glimmer

**Comment by thec0keman** [comment]
That's a great point.  GlimmerJS introduces a new syntax for components, and Emblem does not support this.  There was some initial work on angle bracket components a year ago, but that was stopped when it became clear Ember had not settled on a syntax.

I don't think it would take a lot to support the GlimmerJS syntax.  Do we know if Ember is planning on using a similar syntax?

**Comment by auvipy** [comment]
ember will gradually adapt changes from glimmers eventually

**Comment by thec0keman** [comment]
CC @machty what do you think?

**Comment by thec0keman** [comment]
FWIW [this](https://github.com/emberjs/rfcs/pull/226/files#diff-9fb7c606064a0913ce2d243db70a9ed3R77) RFC outlines some of the areas of convergence and divergence of Ember and Glimmer.

**Comment by machty** [comment]
Confirm, a lot of the details will be fleshed out in that RFC; I'd be happy to make the necessary Emblem changes as things solidify more :)

**Comment by thec0keman** [comment]
Sounds good!  I'm willing to help out too, just been hesitant to start until the API is ready.

**Comment by thec0keman** [comment]
FYI on master this syntax should be working.  Would be great to test and confirm

**Comment by thec0keman** [comment]
I'm going to close this for now.  The test suite has [several](https://github.com/machty/emblem.js/blob/master/tests/integration/glimmer-component-test.js) examples of glimmer components.  I'm not sure if we are 100% to full glimmer support, but if not we are close!
