### ISSUE TITLE
HTML5 boolean attribute on a component

### ISSUE THREAD

**Issue by divmgl** [machty/emblem.js#299]
I need to add an HTML5 boolean attribute to a component. Here's the Handlebars syntax.

```handlebars
{{#my-component data-test-my-component}}
{{/my-component}}
```

However, in Emblem.js this doesn't seem possible. Here's a few variations I've tried:

```
= my-component data-test-my-component [
  some-other-attr='']

= my-component [
  data-test-my-component
  some-other-attr='' ]
```

Does Emblem.js support this?

**Comment by divmgl** [comment]
This issue is related to https://github.com/machty/emblem.js/issues/120

However, https://github.com/machty/emblem.js/issues/120 only mentions a regular tag, not a component. For now I've worked around this by doing:

```
div data-test-my-component=true = my-component [
  some-other-attr='' ]
```

**Comment by thec0keman** [comment]
@divmgl can you confirm if this is valid Ember syntax?
```
{{#my-component data-test-my-component}}
{{/my-component}}
```

For components, aren't you supposed to use `attributeBindings` within the JS file for the component for defining data attributes (for example [here](https://guides.emberjs.com/v2.16.0/templates/binding-element-attributes/#toc_adding-data-attributes) in the guides)?

**Comment by divmgl** [comment]
@thec0keman I'm not sure about that (relatively new to Ember) but turns out I wasn't using valid Ember syntax. Boolean attributes need to go first, and all others after.

```
{{! valid }}
{{comments-list data-test-comments post=post}}

{{! compiler error }}
{{comments-list post=post data-test-comments}}
```

Looks like it's working fine in Emblem.

```
power-select [
      data-test-select-type
      onchange=(action selectType)
      options=data.options.types ]
```

Closing.

**Comment by kketch** [comment]
Hey @divmgl **the only way to have that "data-" boolean attribute on the root element of your component is to use `attributeBindings`.** And this is not related to emblem, the same is true with handlebars.

As explained in issue #120 the `div attribute-name=true` syntax allows you to render boolean html attributes.

But In the example you gave initially, `data-test-my-component` is expected to be the value for a positional parameter, see: https://guides.emberjs.com/v2.16.0/components/passing-properties-to-a-component/#toc_positional-params

So it won't be bound to an html attribute, Ember will rather look for a `data-test-my-component` property on your rendering context (component, controller) and pass the value of that property as the value for positional parameter, which isn't what you want.

And regarding emblem and positional params the only way to use them is to use the regular inline syntax for attributes (no brackets).

**Comment by thec0keman** [comment]
Emblem does support position params inside blocks:

```
= foo-bar [
  'hi!'
  baz=1
]
```

=> [example](https://mammothhr.github.io/try-emblem/#/?result=%3D%20foo-bar%20%5B%0A%20%20'hi!'%0A%20%20baz%3D1%0A%5D)
=> [test](https://github.com/machty/emblem.js/blob/master/tests/integration/mustaches-test.js#L363)
