### ISSUE TITLE
Mulit-line `as |item|` not supported

### ISSUE THREAD

**Issue by samdemaeyer** [machty/emblem.js#306]
Either its not documented, or its just not supported.
This works fine: 
```emblem 
= my-component attributes=attribute conditions=conditions model=model size=size as |item|
  = item
```
These will break:
```emblem 
= my-component [
    attributes=attributes
    conditions=conditions
    model=model
    size=size
    as |item| ]
      = item

= my-component [
    attributes=attributes
    conditions=conditions
    model=model
    size=size ] as |item|
      = item

= my-component [
    attributes=attributes
    conditions=conditions
    model=model
    size=size as ] |item|
      = item

= my-component [
    attributes=attributes
    conditions=conditions
    model=model
    size=size ]
    as |item|
      = item
```

**Comment by thec0keman** [comment]
I think this is a combination of 
- outdated documentation
- some possible gaps in the existing syntas

It can work a few ways:
```
= my-component [
    attributes=attributes
    conditions=conditions
    model=model
    size=size 
] as |item|
      = item
```
[Example](https://mammothhr.github.io/try-emblem/#/?result=%3D%20my-component%20%5B%0A%20%20%20%20attributes%3Dattributes%0A%20%20%20%20conditions%3Dconditions%0A%20%20%20%20model%3Dmodel%0A%20%20%20%20size%3Dsize%20%0A%5D%20as%20%7Citem%7C%0A%20%20%20%20%20%20%3D%20item%0A)

```
= my-component [
    attributes=attributes
    conditions=conditions
    model=model
    size=size ] as |item|
    = item
```
[Example](https://mammothhr.github.io/try-emblem/#/?result=%3D%20my-component%20%5B%0A%20%20%20%20attributes%3Dattributes%0A%20%20%20%20conditions%3Dconditions%0A%20%20%20%20model%3Dmodel%0A%20%20%20%20size%3Dsize%20%5D%20as%20%7Citem%7C%0A%20%20%20%20%3D%20item%0A)

**Comment by samdemaeyer** [comment]
Ah .. I see .. its not because of the `as |item|` that the build error occurs, its because of the wrong indentation of `= item` 🙄 
My bad, thanks for the info @thec0keman! Closing issue now 👍
