### ISSUE TITLE
Please publish 11.1 on NPM

### ISSUE THREAD

**Issue by ilovethebends** [machty/emblem.js#327]

**Comment by thec0keman** [comment]
Sorry about missing this.  The build system for Emblem fell pretty far out of date, and I was running into issues building Emblem on newer versions of node.  0.12 has a rebuilt build system and works just fine on modern node, and other than that only has bugfixes so it should be compatible with 0.11.

**Comment by ilovethebends** [comment]
@thec0keman Sorry i was referring to [NPM](https://www.npmjs.com/package/ember-cli-emblem)
I still see `0.10.0`.

Thank you so much!
