### ISSUE TITLE
Compilation always fails on top level element without a helpful error message

### ISSUE THREAD

**Issue by darthdeus** [machty/emblem.js#48]
[The code in the gist](https://gist.github.com/darthdeus/cea55df6659daecad39a) will fail with

```
Pre compilation failed for: .row.user-profile
  .span3
    .avatar
      img src={image}
```

while the actual error is on line 36, which should instead be 

```
= linkTo .help-inline "users.index" | back to users
```

the only way to debug this is randomly removing segments of the code to see which part breaks it.

**Comment by thec0keman** [comment]
Moved to #276
